name: CI
on: [push, pull_request]
jobs:
  dockerLint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
    - name: Dump Event Payload
      run: cat ${GITHUB_EVENT_PATH}
    - uses: actions/checkout@master
    - name: Docker Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile
    - name: swift test on push
      if: github.event_name == 'push'
      uses: docker://norionomura/swiftlint:swift-5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: swift
        args: test
    - name: swift test on pull_request
      if: github.event_name == 'pull_request' && contains('opened synchronize reopened', github.event.action)
      uses: docker://norionomura/swiftlint:swift-5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACTION_SWIFTLINT_SHA: ${{ github.event.pull_request.head.sha }}
      with:
        entrypoint: swift
        args: test
    - name: Docker Build
      uses: actions/docker/cli@master
      with:
        args: build -t action-swiftlint .
